### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by GuacheSuede** [gokulkrishh/demo-progressive-web-app#3]
Hello @gokulkrishh 

Curious question, is it possible to run this on IOS and if so how would one do so ? 

Thank You,
GuacheSuede

**Comment by gokulkrishh** [comment]
@GuacheSuede Good question. Since `service worker api` are not supported in iOS yet.

Refer here: https://jakearchibald.github.io/isserviceworkerready/

Also for iOS `service worker` is still under consideration - https://webkit.org/status/#specification-service-workers. So for now only supports in android chrome, firefox & opera

**Comment by gokulkrishh** [comment]
I guess this addresses @GuacheSuede your question. So closing the issue. If you have any question. Shoot them up
